### ISSUE TITLE
latest versions of tidy5e sheet break compatibility. 

### ISSUE THREAD

**Issue by dirusulixes** [ktrieun/FVTT-5e-exchange-rate#1]
See this https://github.com/sdenec/tidy5e-sheet/issues/187
I thought to open an issue here as well if only to update the readme.

**Comment by sdenec** [comment]
For the next update I have added custom localization strings to tidy5e:

'TIDY5E.CurrencyAbbrCP' : "CP",
'TIDY5E.CurrencyAbbrSP' : "SP",
'TIDY5E.CurrencyAbbrGP' : "GP",
'TIDY5E.CurrencyAbbrEP' : "EP",
'TIDY5E.CurrencyAbbrPP' : "PP"

Since the default translations are drawn from god knows where and I'm unable to modify the template files to insert my abbreviated ones I now simply replace the label text with the right abbreviation via script. So I don't know if this is in any way helpful to fix the compatibility issue ... If you somehow alter the Translations string though it should help.

**Comment by ktrieun** [comment]
Are you pulling from data.currency and iterating through to get the labels of the currencies?

**Comment by InfraredAces** [comment]
I added settings so that the user can enter their own currency abbreviations and added a function that will change the currency abbreviation text displayed shown on render so my module is now compatible with the current version of Tidy5e Sheet.
